/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Liveness probe for API availability.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description User authentication for role-based access (Owner / Staff).
         *     Supports: US-11.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search customers
         * @description Search customers by name or contact number.
         *     Supports: US-01 (customer selection for order intake).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Free-text search by name or contact (optional) */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customers list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create customer
         * @description Creates a customer with first name, last name, contact number.
         *     Supports: US-01. Enforces: BR-REC-01.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCustomerRequest"];
                };
            };
            responses: {
                /** @description Customer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer by ID
         * @description Supports: US-01.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List service rates
         * @description Returns pricing rules (load, 8 kg limit, extra minute rate).
         *     Supports: US-02 (order intake form).
         */
        get: {
            parameters: {
                query?: {
                    activeOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service rates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRateResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-rates/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active service rate
         * @description Returns the active rate used for order pricing (default).
         *     Supports: US-02. Enforces: BR-PR-01, BR-PR-02, BR-PR-03.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active rate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRateResponse"];
                    };
                };
                /** @description No active rate configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search orders
         * @description Returns orders with pagination and optional filters.
         *     Supports: US-01, US-03, US-07.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["OrderStatus"];
                    paymentStatus?: components["schemas"]["PaymentStatus"];
                    /** @description Start date (inclusive) */
                    from?: string;
                    /** @description End date (inclusive) */
                    to?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated orders list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create laundry order
         * @description Creates order with automatic pricing (loads, extra minutes, add-ons).
         *     Generates unique reference number. Sets initial status RECEIVED.
         *     Supports: US-01, US-02. Enforces: BR-PR-01, BR-PR-02, BR-PR-03, BR-PR-04, BR-OL-01, BR-OL-02.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Order created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Validation or business rule error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order by ID
         * @description Supports: US-03, US-05, US-06.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/reference/{referenceNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track order by reference number
         * @description Public endpoint for customer tracking. Returns limited data (no internal IDs).
         *     Supports: US-04. Enforces: BR-NOTIF-02, BR-OL-01.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    referenceNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order tracking view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderTrackingResponse"];
                    };
                };
                /** @description Reference not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order status
         * @description Updates status and records change in order_status_logs.
         *     Supports: US-03, US-05. Enforces: BR-OL-03, BR-OL-04, BR-OL-05.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderStatusRequest"];
                };
            };
            responses: {
                /** @description Updated order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Invalid transition or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payments
         * @description Returns payments with pagination and optional filters.
         *     Supports: US-07.
         */
        get: {
            parameters: {
                query?: {
                    orderId?: number;
                    /** @description Start date (inclusive) */
                    from?: string;
                    /** @description End date (inclusive) */
                    to?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated payments list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Record payment for order
         * @description Records payment. One payment per order. MVP: amount must equal order grand total.
         *     Supports: US-06. Enforces: BR-PAY-02, BR-PAY-03, BR-PAY-04.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePaymentRequest"];
                };
            };
            responses: {
                /** @description Payment recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description Validation or amount mismatch */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment by ID
         * @description Supports: US-07.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications
         * @description Returns all notifications (staff view).
         *     Supports: US-10. Enforces: BR-NOTIF-01.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notifications list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily sales report
         * @description Aggregates income from payments for the given date.
         *     Supports: US-08. Enforces: BR-REC-01, BR-PAY-04.
         */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Daily sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailySalesReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly sales report
         * @description Aggregates income from payments for the given month.
         *     Supports: US-09. Enforces: BR-REC-01, BR-PAY-04.
         */
        get: {
            parameters: {
                query: {
                    year: number;
                    month: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monthly sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PeriodSalesReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yearly sales report
         * @description Aggregates income from payments for the given year.
         *     Supports: US-09. Enforces: BR-REC-01, BR-PAY-04.
         */
        get: {
            parameters: {
                query: {
                    year: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Yearly sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PeriodSalesReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example weight_kg must be greater than 0 */
            message: string;
            details?: string[];
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT token */
            token: string;
            role: components["schemas"]["UserRole"];
        };
        /** @enum {string} */
        UserRole: "OWNER" | "STAFF";
        /** @enum {string} */
        OrderStatus: "RECEIVED" | "WASHING" | "DRYING" | "FOLDING" | "READY_FOR_PICKUP" | "RELEASED" | "CANCELLED";
        /** @enum {string} */
        PaymentStatus: "UNPAID" | "PAID" | "PARTIAL";
        /** @enum {string} */
        PaymentMethod: "CASH" | "GCASH" | "BANK_TRANSFER";
        /** @enum {string} */
        NotificationStatus: "PENDING" | "SENT" | "FAILED";
        CreateCustomerRequest: {
            firstName: string;
            lastName: string;
            contactNumber: string;
        };
        CustomerResponse: {
            /** Format: int64 */
            id: number;
            firstName: string;
            lastName: string;
            contactNumber: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ServiceRateResponse: {
            id: number;
            serviceName: string;
            /**
             * Format: double
             * @description ₱120 per load (BR-PR-01)
             */
            basePricePerLoad: number;
            /**
             * Format: double
             * @description 8 kg per load (BR-PR-01)
             */
            kgLimitPerLoad: number;
            /**
             * Format: double
             * @description ₱1 per extra minute (BR-PR-03)
             */
            pricePerExtraMinute: number;
            isActive: boolean;
        };
        /** @description Provide either customerId OR customer (create on the fly). weightKg required. extraMinutes and initialAddOns optional. */
        CreateOrderRequest: {
            /**
             * Format: int64
             * @description Existing customer ID
             */
            customerId?: number;
            /**
             * Format: uuid
             * @description User creating the order. Required until auth (Phase 9).
             */
            createdByUserId?: string;
            customer?: components["schemas"]["CreateCustomerRequest"];
            /**
             * Format: double
             * @description Laundry weight in kg
             */
            weightKg: number;
            /**
             * @description Extra washing minutes beyond 45 min per load
             * @default 0
             */
            extraMinutes: number;
            initialAddOns?: components["schemas"]["AddOnInput"][];
        };
        AddOnInput: {
            name: string;
            /** Format: double */
            price: number;
            /** @default 1 */
            quantity: number;
        };
        UpdateOrderStatusRequest: {
            newStatus: components["schemas"]["OrderStatus"];
            notes?: string;
            /**
             * Format: uuid
             * @description User who initiated the status change (required until Phase 9 authentication)
             */
            changedByUserId: string;
        };
        AddOrderAddOnRequest: {
            name: string;
            /** Format: double */
            price: number;
            /** @default 1 */
            quantity: number;
        };
        OrderResponse: {
            /** Format: int64 */
            id: number;
            /** @description Unique tracking identifier */
            referenceNumber: string;
            /** Format: int64 */
            customerId: number;
            /** Format: uuid */
            createdByUserId?: string;
            /** Format: double */
            weightKg: number;
            /** @description ceil(weight_kg / kg_limit_per_load) */
            totalLoads: number;
            extraMinutes?: number;
            /** Format: double */
            baseAmount: number;
            /** Format: double */
            extraMinutesAmount: number;
            /** Format: double */
            addonsTotalAmount: number;
            /** Format: double */
            grandTotal: number;
            currentStatus: components["schemas"]["OrderStatus"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        OrderPageResponse: {
            content: components["schemas"]["OrderResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        PaymentPageResponse: {
            content: components["schemas"]["PaymentResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        OrderTrackingResponse: {
            referenceNumber: string;
            currentStatus: components["schemas"]["OrderStatus"];
            customerName: string;
            contactNumber?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: double */
            grandTotal?: number;
            paymentStatus: components["schemas"]["PaymentStatus"];
        };
        CreatePaymentRequest: {
            /** Format: int64 */
            orderId: number;
            /**
             * Format: double
             * @description Must equal order grand total (BR-PAY-03)
             */
            amountPaid: number;
            paymentMethod?: components["schemas"]["PaymentMethod"];
            /**
             * Format: uuid
             * @description User recording the payment. Required until auth (Phase 9).
             */
            receivedByUserId: string;
        };
        PaymentResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            orderId: number;
            /** Format: double */
            amountPaid: number;
            paymentMethod: components["schemas"]["PaymentMethod"];
            /** Format: uuid */
            receivedByUserId?: string;
            /** Format: date-time */
            paymentDate: string;
            remarks?: string;
        };
        NotificationResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            orderId: number;
            referenceNumber?: string;
            /** Format: int64 */
            customerId: number;
            customerName?: string;
            contactNumber?: string;
            message: string;
            status: components["schemas"]["NotificationStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            sentAt?: string;
        };
        DailySalesReportResponse: {
            /** Format: date */
            date: string;
            /** Format: double */
            totalIncome: number;
            paidOrdersCount: number;
        };
        PeriodSalesReportResponse: {
            /** @example 2026-02 */
            period: string;
            /** Format: double */
            totalIncome: number;
            paidOrdersCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
