export const dynamic = {
  ELEVATING_THE: `ELEVATING THE`,
  LAUNDRY: `LAUNDRY`,
  EXPERIENCE: `EXPERIENCE`,
  STREAMLINING_EVERY_LOAD__WASH: `Streamlining every load, wash, and fold with professional-grade management tools. 
            Designed for the modern garment care professional.`,
  COPY: `&copy;`,
  BULL: `&bull;`,
  STR_0616fb: `→`,
  STR_01abfc: `#`,
  THE_CUSTOMER_YOU_ARE_LOOKING_F: `The customer you are looking for might have been moved or archived.`,
  ORDER_RECEIVED: `Order Received`,
  STR_853ae9: `:`,
  STR_ecb201: `⚠️`,
  SYSTEM_OPERATIONS_ARE_CURRENTL: `System operations are currently paused due to a power interruption. Washing and drying machines cannot be started.`,
  COMING_SOON: `Coming Soon`,
  THE_MESSAGING_FEATURE_IS_CURRE: `The Messaging feature is currently under active development. 
          Soon, you&apos;ll be able to send automated SMS notifications to customers when their laundry is ready for pickup.`,
  STR_b99834: `|`,
  ASSIGNED_MACHINES: `Assigned Machines`,
  LOADING_MACHINES: `Loading machines...`,
  NO_MACHINES_AVAILABLE: `No machines available`,
  STR_eb6439: `&quot;`,
  STR_26b172: `+`,
  X: `(x`,
  STR_9371d7: `)`,
  REFERENCE_NUMBER___TRACE_ID: `Reference Number / Trace ID`,
  PER: `Per`,
  LOAD: `load`,
  SITIO_ILAYA__TABUC_SUBA_JARO: `Sitio Ilaya, Tabuc Suba Jaro,`,
  ILOILO_CITY__5000_PHILIPPINES: `Iloilo City, 5000 Philippines`,
  PHONE___INQUIRIES: `Phone & Inquiries`,
  MON___SAT__8_00_AM___7_00_PM: `Mon — Sat: 8:00 AM - 7:00 PM`,
  ALL_RIGHTS_RESERVED: `• All Rights Reserved`,
  EXPERIENCE_THE_EVOLUTION_OF: `. Experience the evolution of local laundry with our Real-Time Tracking.`,
  CLEAR_SEARCH: `Clear Search`,
  WE_LOOK_FORWARD_TO_SEEING_YOU: `We look forward to seeing you again!`,
  BULL__2026: `&bull; 2026`,
  "404": `404`,
  ACTIVITY_OVERVIEW: `Activity Overview`,
  STR_53fe08: `•`,
  ID: `ID:`,
  PREVIOUS_STATE: `Previous State`,
  NEW_STATE: `New State`,
  NO_SPECIFIC_FIELD_CHANGES_RECO: `No specific field changes recorded for this activity.`,
  PERFORMED_BY: `Performed By`,
  TIMESTAMP: `Timestamp`,
  DELIVERY_OVERVIEW: `Delivery Overview`,
  OUTGOING_SMS_CONTENT: `Outgoing SMS Content`,
  ORDER_CONTEXT: `Order Context`,
  DISPATCH_TIME: `Dispatch Time`,
  VIEW_ORDER: `View Order`,
  CLOSE_DETAILS: `Close Details`,
  STR_6666cd: `/`,
  SYSTEM_IS_PAUSED__POWER_INTERR: `System is Paused (Power Interruption Mode)`,
  YOU_CANNOT_START_NEW_WASHING_O: `You cannot start new WASHING or DRYING processes until power is restored and the system is unpaused.`,
  SITIO_ILAYA__TABUC_SUBA__JARO: `SITIO ILAYA, TABUC SUBA, JARO, ILOILO CITY`,
  "63_929_155_4954": `+63 929 155 4954`,
  CLAIM_STUB: `CLAIM STUB`,
  ITEM___SERVICE: `ITEM / SERVICE`,
  PRICE: `PRICE`,
  STR_518ed2: `@`,
  KG: `KG`,
  EXTRA_MINUTES: `EXTRA MINUTES (`,
  MINS: `MINS)`,
  ADD_ONS: `Add-ons`,
  X_327d: `(X`,
  ADD_ONS_TOTAL: `Add-ons Total`,
  SUBTOTAL: `SUBTOTAL:`,
  GRAND_TOTAL: `Grand Total:`,
  PAYMENT_STATUS: `PAYMENT STATUS:`,
  BALANCE_DUE: `BALANCE DUE:`,
  TERMS_AND_CONDITIONS: `TERMS AND CONDITIONS`,
  PRESENT_THIS_STUB_TO_CLAIM_LAU: `PRESENT THIS STUB TO CLAIM LAUNDRY. NO STUB, NO RELEASE.`,
  NOT_RESPONSIBLE_FOR_COLOR_BLEE: `NOT RESPONSIBLE FOR COLOR BLEED, SHRINKAGE, OR BUTTON LOSS.`,
  LIABILITY_FOR_LOST_ITEMS_IS_LI: `LIABILITY FOR LOST ITEMS IS LIMITED TO 3X THE SERVICE FEE.`,
  UNCLAIMED_ITEMS_AFTER_30_DAYS: `UNCLAIMED ITEMS AFTER 30 DAYS WILL BE DISPOSED OR DONATED.`,
  CHECK_ALL_ITEMS_UPON_CLAIMING: `CHECK ALL ITEMS UPON CLAIMING. NO COMPLAINTS AFTER RELEASE.`,
  UNPAID_ORDERS_MUST_BE_SETTLED: `UNPAID ORDERS MUST BE SETTLED BEFORE RELEASING ITEMS.`,
  CUSTOMER_SIGNATURE: `CUSTOMER SIGNATURE`,
  THANK_YOU_FOR_TRUSTING: `THANK YOU FOR TRUSTING`,
  FAITH_LAUNDRY_SHOP: `FAITH LAUNDRY SHOP!`,
  DONE: `Done`,
  SAVE: `Save`,
  PRINT: `Print`,
  NO_MATCHING_CUSTOMERS_FOUND: `No matching customers found`,
  REGISTER__QUOT: `Register &quot;`,
  OR: `Or`,
  REGISTER_NEW_CUSTOMER: `Register New Customer`,
  VERIFIED: `Verified`,
  MEMBER_ACCOUNT: `Member Account`,
  REGISTERING_NEW_ACCOUNT: `Registering New Account`,
  BACK_TO_SEARCH: `Back to search`,
  MINS_c047: `MINS`,
  ADD_CONSUMABLES_OR_SPECIAL_INS: `Add consumables or special instructions.`,
  ADD: `Add`,
  SPECIAL_INSTRUCTIONS: `Special Instructions`,
  ASSIGN_MACHINES: `Assign Machines`,
  GRAND_TOTAL_1985: `Grand Total`,
  PAYMENT_METHOD: `Payment Method`,
  REFERENCE_NUMBER: `Reference Number`,
  X_9dd4: `x`,
  FAITH_LAUNDRY_SHOP_OFFICIAL_RE: `Faith Laundry Shop Official Receipt Preview`,
  SESSION_TOTAL: `SESSION TOTAL`,
  VS_YESTERDAY: `% vs Yesterday`,
  ACTIVE_ANALYSIS: `Active Analysis`,
  CLICK_TO_INVESTIGATE: `Click to investigate`,
  SYSTEM_SECURITY__ALL_ACCESS_AT: `System Security: All access attempts are logged for audit purposes.`,
  STR_26aeab: `—`,
  FAITH_LAUNDRY_SHOP_2a14: `Faith Laundry Shop`,
  GENERATED: `Generated:`,
  PERFORMANCE_VISUALIZATIONS: `Performance Visualizations`,
  DETAILED_RECORDS: `Detailed Records`,
  PAGE_1_OF_1: `Page 1 of 1`,
  SOON: `Soon`,
  STR_3389da: `*`,
  VS_PREV_PERIOD: `% vs prev period`,
  PROTECTED_CONTENT: `Protected content`,
  ORDERPREVIEW_MOCK: `OrderPreview Mock`,
  STR_a017e2: `📦`,
};
