export const feedback = {
  success: {
    GENERIC: "Operation successful",
    REGISTERED: "Successfully registered",
    UPDATED: "Successfully updated",
    SAVED: "Changes saved successfully",
    ORDER_SAVED: "Order has been added to the list.",
    PAYMENT: "Payment recorded successfully",
    COPIED: "Reference number copied",
  },
  error: {
    GENERIC: "System error occurred",
    SYSTEM_ERROR: "Something went wrong. Please try again.",
    SYSTEM_ERROR_TITLE: "System Error",
    NOT_FOUND: "Could not find that info.",
    NOT_FOUND_PAGE: "Page Not Found",
    NOT_FOUND_DESC: "We couldn't find the page you're looking for. It might have been moved or deleted.",
    AUTH_REQUIRED: "You need to log in to access this feature.",
    ACCESS_DENIED_TITLE: "Access Restricted",
    ACCESS_DENIED_DESC: "You do not have permission to view this.",
    LOAD_FAILED: "Failed to load data.",
  },
  empty: {
    GENERIC_TITLE: "No results found",
    GENERIC_DESC: "Try adjusting your search or filters.",
    AUDIT_LOG_TITLE: "No audit records",
    AUDIT_LOG_DESC: "System events and security logs will appear here automatically.",
    CLIENT_ALERTS_TITLE: "No alerts logged",
    CLIENT_ALERTS_DESC: "Logs of automated SMS alerts sent to customers will appear here.",
    ORDERS_TITLE: "Queue is empty",
    ORDERS_DESC: "Incoming orders will appear here automatically.",
    CUSTOMERS_TITLE: "No customers found",
    CUSTOMERS_DESC: "Register a customer by starting a new order.",
    PAYMENTS_TITLE: "No Transactions Found",
    PAYMENTS_DESC: "Completed payments will appear here.",
    SALES_TITLE: "No Sales Data",
    SALES_DESC: "Revenue data will appear once payments are recorded.",
    SEARCH_TITLE: "No matches found",
  },
} as const;
