export const forms = {
  intake: {
    TITLE: "New Order",
    SUBTITLE: "Record a drop-off",
    CUSTOMER_SECTION: "Customer Details",
    SEARCH_LABEL: "Existing Customer",
    SEARCH_PLACEHOLDER: "Search by name or phone...",
    BACK_TO_SEARCH: "Back to Customer Search",
    WEIGHT_HINT: "Standard load is 8 kg",
    EXTRA_TIME_HINT: "Add minutes for extra drying",
    PRICING_SUMMARY: "Pricing Summary",
    EMPTY_PRICING: "Enter weight to calculate price",
    COLLECT_PAYMENT: "Collect Payment Now",
    SUBMIT_BUTTON: "Submit",
    SELECT_CUSTOMER: "Select Customer",
    SELECT_CUSTOMER_DESC: "Identify the customer for this service request.",
    SERVICE_DETAILS: "Service Details",
    SERVICE_DETAILS_DESC: "Configure the laundry parameters.",
    REVIEW_PAYMENT: "Review & Payment",
    REVIEW_PAYMENT_DESC: "Finalize the order and process payment.",
    SUCCESS_TITLE: "Order Created Successfully",
    VERIFY_WEIGHT: "Please verify weight before finalizing",
    STEP_BAG: "What's in the bag?",
    STEP_SERVICE: "Service type",
    STEP_FINAL: "Final details",
    FIND_CUSTOMER: "Find Customer",
    NEW_CUSTOMER: "New Customer",
    ADDONS: "Add-ons (Optional)",
    EXTRA_MINS: "Extra Minutes",
    ADD_ON_NAME: "Add-on Name",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    CONTACT: "Contact Number",
  },
  checkout: {
    TITLE: "Collect Payment",
    SUBTITLE: "Settle a balance",
    AMOUNT: "Amount to Pay",
    METHOD: "Payment Method",
    SETTLE: "Settle Balance",
    ALREADY_PAID: "This order is already paid.",
    SUCCESS_TITLE: "Payment Recorded",
    SUCCESS_SUBTITLE: "The balance has been settled.",
    FINAL_AMOUNT: "Amount to Pay",
    RECEIVED: "Amount Received",
    STILL_DUE: "Still Due",
    TRACKING_NUMBER: "Tracking Number",
    PAYMENT_METHOD: "Payment Method",
    PAY_VIA: "Pay via",
    PAY_CASH: "Pay with Cash",
  },
  payment: {
    TITLE: "Payment Processing",
    AMOUNT_LABEL: "Amount to Pay",
    SUBMIT_BUTTON: "Process Payment",
  },
} as const;
