export const portal = {
  topnav: {
    OFFICIAL_WEBSITE: "Official Website",
    OFFICIAL_PORTAL: "Official Customer Portal",
    STAFF_PORTAL: "Staff Operations Portal",
  },
  landing: {
    HERO_TITLE_1: "YOUR LAUNDRY.",
    HERO_TITLE_2: "TRACKED FROM",
    HERO_TITLE_3: "DROP-OFF TO PICKUP.",
    HERO_SUBTITLE: "The most reliable laundry service in Sitio Ilaya, Tabuc Suba Jaro. Experience the evolution of local laundry with our Real-Time Tracking System.",
    TRUSTED_SINCE: "Trusted Since 2022",
    CUSTOMER_RATING: "5.0 Customer Rating",
    TRACKING_BUTTON: "Laundry Tracker →",
    TRACKING_HINT: "Check your receipt for your 15-character tracking number.",
    VISIT_US: "Visit Us Today",
    COMMITMENT_TITLE: "Our Commitment",
    COMMITMENT_H1: "Modern Care for Your Clothes.",
    COMMITMENT_DESC: "We combine traditional cleanliness with the transparency of modern technology.",
    PRICING_TITLE: "Simple & Honest Pricing",
    PRICING_H1: "CLEAR PRICING. NO HIDDEN FEES.",
    PRICING_DESC: "We keep it simple. ₱120 covers a standard 8 kg basket—perfect for your weekly wash.",
    PRICING_ITEM_1: "Standard Wash, Dry & Fold",
    PRICING_ITEM_2: "Premium Detergent Included",
    PRICING_ITEM_3: "+₱1 per additional washminute",
    PRICING_ITEM_4: "Online Status Tracking",
    PRICING_CARD_TITLE: "The Daily Standard",
    PRICING_CARD_SUB: "Per Load (Up to 8 kg)",
    LOCATION_TITLE: "Visit the Shop",
    SUPPORT_TITLE: "Direct Support",
    RESPONSE_TIME: "Average Response:",
    RESPONSE_VALUE: "15 Mins",
    HIGHLIGHTS: {
      REALTIME_TRACKING_TITLE: "Real-Time Tracking",
      REALTIME_TRACKING_DESC: "Track your order status anytime, anywhere.",
      SAFE_SECURE_TITLE: "Safe & Secure",
      SAFE_SECURE_DESC: "Your items are handled with care.",
      FAST_TURNAROUND_TITLE: "Fast Turnaround",
      FAST_TURNAROUND_DESC: "Quality service, delivered on time.",
      CUSTOMER_FIRST_TITLE: "Customer First",
      CUSTOMER_FIRST_DESC: "We're here to make your life easier.",
    },
    FEATURES: {
      LIVE_UPDATES: "Live Status Updates",
      LIVE_UPDATES_DESC: "No need to wonder or wait. Enter your receipt number to see exactly when your clothes hit the washer, dryer, and folding table.",
      DEDICATED_LOADS: "Dedicated Machine Loads",
      DEDICATED_LOADS_DESC: "We sort carefully and never mix your garments with other customers' orders. Your clothes get their own dedicated wash and dry cycles.",
      DIGITAL_ACCOUNTABILITY: "100% Digital Accountability",
      DIGITAL_ACCOUNTABILITY_DESC: "Say goodbye to manual logbooks and mixed-up items. Our digital system logs every load from drop-off to pickup.",
    }
  },
  tracking: {
    TITLE: "Laundry Tracker",
    OFFICIAL_LABEL: "Official Tracking Portal",
    PROMPT: "Track your laundry in real time.",
    PROMPT_SUBTITLE: "Enter the tracking number from your receipt to check your order status.",
    ERROR_PROMPT: "TRACKING NUMBER NOT FOUND",
    PLACEHOLDER: "LDR-YYYYMMDD-XXXX",
    BUTTON_FIND: "Find Order",
    BUTTON_TRY_AGAIN: "Try Again",
    SYNCING: "Syncing with live feed...",
    CURRENT_PROGRESS: "Current Progress",
    LIVE_UPDATE: "Live Update",
    RECEIVED_ON: "Received",
    COPY_REF: "Copy tracking number",
    COPY_TITLE: "Copy Tracking Number",
    TAP_TO_COPY: "Tap to copy",
    CLAIM_INSTRUCTION_PREFIX: "Please present tracking number",
    CLAIM_INSTRUCTION_SUFFIX: "when you come to claim your laundry.",
    KEEP_SAFE_REMINDER: "Keep your tracking number safe. You'll need it when you pick up your order.",
    NOT_FOUND_DESC: "We couldn't find an order for that tracking number. Check the number on your receipt and try again.",
    SUPPORT_LABEL: "Support Line",
    SUPPORT_PHONE: "0929-155-4954",
    OFFICIAL_PORTAL: "Official Tracking Portal",
    REAL_TIME_SYNC: "Real-Time Sync",
    VERIFIED_DATA: "Verified Data",
    OFFICIAL_RECEIPT_ONLY: "Official Receipt Only",
    STATUS_MSG: {
      RECEIVED: "Your order has been received and is currently in the queue.",
      WASHING: "Your clothes are currently in the washing machine.",
      DRYING: "Your laundry is now in the drying cycle.",
      FOLDING: "We are currently folding and packing your clothes.",
      READY_FOR_PICKUP: "Great news! Your laundry is ready for collection.",
      RELEASED: "Order has been claimed. Thank you for choosing Faith Laundry!",
      CANCELLED: "This order has been cancelled.",
    } as Record<string, string>,
    FALLBACK_PROGRESS: "We are working on your order. Check back soon!",
    CLEAR_SEARCH: "Clear Search",
    SUCCESS_HEADER: "Success",
    SEE_YOU_AGAIN: "We look forward to seeing you again!",
  }
} as const;
