export const portal = {
  landing: {
    HERO_TITLE_1: "Laundry Care",
    HERO_TITLE_2: "With a",
    HERO_TITLE_3: "Human Touch.",
    HERO_SUBTITLE: "The most reliable laundry service in Tabuc Suba Jaro. Experience the evolution of local laundry with our Real-Time Tracking System.",
    TRUSTED_SINCE: "Trusted Since 2022",
    CUSTOMER_RATING: "5.0 Customer Rating",
    TRACKING_HINT: "* Check your receipt for your 15-character reference number.",
    VISIT_US: "Visit Us Today",
    COMMITMENT_TITLE: "Our Commitment",
    COMMITMENT_H1: "Modern Care for Your Clothes.",
    COMMITMENT_DESC: "We combine traditional cleanliness with the transparency of modern technology.",
    PRICING_TITLE: "Simple & Honest Pricing",
    PRICING_H1: "CLEAR PRICING. NO HIDDEN FEES.",
    PRICING_DESC: "We keep it simple. ₱120 covers a standard 8 kg basket—perfect for your weekly wash.",
    PRICING_ITEM_1: "Standard Wash, Dry & Fold",
    PRICING_ITEM_2: "Premium Detergent Included",
    PRICING_ITEM_3: "Strict 8 kg Limit per Machine Load",
    PRICING_ITEM_4: "Online Status Tracking",
    PRICING_CARD_TITLE: "The Daily Standard",
    PRICING_CARD_SUB: "Per Load (Up to 8 kg)",
    LOCATION_TITLE: "Visit the Shop",
    SUPPORT_TITLE: "Direct Support",
    RESPONSE_TIME: "Average Response:",
    RESPONSE_VALUE: "15 Mins",
    FEATURES: {
      LIVE_UPDATES: "Live Status Updates",
      LIVE_UPDATES_DESC: "No need to wonder or wait. Enter your receipt number to see exactly when your clothes hit the washer, dryer, and folding table.",
      DEDICATED_LOADS: "Dedicated Machine Loads",
      DEDICATED_LOADS_DESC: "We sort carefully and never mix your garments with other customers' orders. Your clothes get their own dedicated wash and dry cycles.",
      DIGITAL_ACCOUNTABILITY: "100% Digital Accountability",
      DIGITAL_ACCOUNTABILITY_DESC: "Say goodbye to manual logbooks and mixed-up items. Our digital system logs every load from drop-off to pickup.",
    }
  },
  tracking: {
    TITLE: "Laundry Tracker",
    OFFICIAL_LABEL: "Official Tracking Portal",
    PROMPT: "Locate your laundry status in real-time.",
    PLACEHOLDER: "LDR-YYYYMMDD-XXXX",
    BUTTON_FIND: "Find Order",
    BUTTON_SHOWING: "Showing Result",
    SYNCING: "Syncing with live feed...",
    CURRENT_PROGRESS: "Current Progress",
    LIVE_UPDATE: "Live Update",
    RECEIVED_ON: "Received",
    COPY_REF: "Copy reference number",
    COPY_TITLE: "Copy Reference",
    TAP_TO_COPY: "Tap to copy",
    CLAIM_INSTRUCTION_PREFIX: "Please present reference number",
    CLAIM_INSTRUCTION_SUFFIX: "when you come to claim your laundry.",
    KEEP_SAFE_PREFIX: "Keep your reference number",
    KEEP_SAFE_SUFFIX: "safe. You will need it to collect your order.",
    NOT_FOUND_DESC: "We couldn't find an order matching that reference. Please check your physical receipt.",
    SUPPORT_LABEL: "Support Line",
    SUPPORT_PHONE: "0929-155-4954",
    OFFICIAL_PORTAL: "Official Tracking Portal",
    REAL_TIME_SYNC: "Real-Time Sync",
    VERIFIED_DATA: "Verified Data",
    OFFICIAL_RECEIPT_ONLY: "Official Receipt Only",
    STATUS_MSG: {
      RECEIVED: "Your order has been received and is currently in the queue.",
      WASHING: "Your clothes are currently in the washing machine.",
      DRYING: "Your laundry is now in the drying cycle.",
      FOLDING: "We are currently folding and packing your clothes.",
      READY_FOR_PICKUP: "Great news! Your laundry is ready for collection.",
      RELEASED: "Order has been claimed. Thank you for choosing Faith Laundry!",
      CANCELLED: "This order has been cancelled.",
    } as Record<string, string>,
    FALLBACK_PROGRESS: "We are working on your order. Check back soon!",
  }
} as const;
