export const shared = {
  common: {
    ID: "ID",
    ORDER_NUMBER: "Order #",
    DATE: "Date",
    TIME: "Time",
    TOTAL: "Total",
    STATUS: "Status",
    ACTIONS: "Actions",
    SEARCH: "Search",
    FILTER: "Filter",
    REFRESH: "Refresh",
    HELP: "Help",
    SYSTEM: "System",
    DETAILS: "Details",
    CUSTOMER: "Customer",
    SERVICE: "Service Type",
    EXTRA_TIME: "Extra Time",
    NAME: "Name",
    CONTACT: "Contact",
    REFERENCE: "Reference",
    AMOUNT_DUE: "Amount Due",
    METHOD: "Method",
    USER: "User",
    STAFF: "Staff",
    ADMIN: "Admin",
    ROLE: "Role",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    LIVE: "Live",
    START_DATE: "Start Date",
    END_DATE: "End Date",
    ALL_STATUSES: "All Statuses",
    ALL_PAYMENTS: "All Payments",
    ALL_ACTIONS: "All Actions",
    SEARCH_PLACEHOLDER: "Search registry...",
    CONTACT_PLACEHOLDER: "e.g. 09123456789",
    REF_PLACEHOLDER: "e.g. LDR-20261001-1234",
    CALCULATING: "Calculating...",
    BASE_PRICE: "Base Price",
    LOADING: "Loading...",
    SUCCESS: "Success",
    FAILURE: "Failure",
    UNKNOWN: "Unknown",
  },

  buttons: {
    SAVE: "Save",
    CANCEL: "Cancel",
    DISCARD: "Discard",
    EDIT: "Edit",
    MODIFY: "Modify",
    DELETE: "Delete",
    BACK: "Back",
    NEXT: "Next",
    RETRY: "Try Again",
    VIEW_ALL: "View All",
    LOGOUT: "Log Out",
    SUBMIT: "Submit",
    CREATE: "Create",
    UPDATE: "Update",
    CONFIRM: "Confirm",
    DONE: "Done",
    PROCEED: "Proceed",
    COPY: "Copy",
    CHANGE: "Change",
  },

  status: {
    // Order Stages §7.1
    RECEIVED: "Queued",
    WASHING: "Washing",
    DRYING: "Drying",
    FOLDING: "Folding",
    READY_FOR_PICKUP: "Ready",
    RELEASED: "Claimed",
    CANCELLED: "Cancelled",
    // Payment States
    PAID: "Paid",
    UNPAID: "Unpaid",
    PARTIAL: "Partial",
    VOIDED: "Voided",
    REFUNDED: "Refunded",
    // Zone Labels
    QUEUE_ZONE: "Queue",
    WASHING_ZONE: "Washing Zone",
    DRYING_ZONE: "Drying Zone",
    FOLDING_ZONE: "Folding Zone",
    READY_ZONE: "Ready for Pickup",
  },

  units: {
    WEIGHT: "KG",
    TIME: "MIN",
    LOAD: "Load",
    LOADS: "Loads",
    CURRENCY: "₱",
    PRICE_SYMBOL: "₱",
    PRICE: "Price",
    CURRENCY_NAME: "PHP",
  },
} as const;
