/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Liveness probe for API availability.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description User authentication for role-based access (Admin / Staff).
         *     Returns an access token in the response body and sets an HTTP-only refresh_token
         *     cookie plus a JavaScript-readable csrf_token cookie for double-submit CSRF protection.
         *     Supports: US-11.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login success */
                200: {
                    headers: {
                        /** @description CSRF value to retain in memory and send on credentialed refresh/logout requests. */
                        "X-CSRF-Token"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the presented refresh token and clears refresh_token and csrf_token cookies.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-CSRF-Token": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid CSRF token */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap CSRF protection
         * @description Issues a csrf_token cookie and returns the matching value in X-CSRF-Token for a cross-origin SPA to retain only in memory.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSRF token issued */
                200: {
                    headers: {
                        /** @description CSRF value to retain in memory and send on credentialed refresh/logout requests. */
                        "X-CSRF-Token"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Session
         * @description Rotates the refresh token and returns a new access token.
         *     Requires valid refresh_token cookie and X-CSRF-Token header.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-CSRF-Token": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refresh success */
                200: {
                    headers: {
                        /** @description Replacement CSRF value to retain in memory and send on the next credentialed request. */
                        "X-CSRF-Token"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Unauthorized / Invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid CSRF token */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the authenticated user's identity based on JWT/Session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search customers
         * @description Search customers by name or contact number.
         *     Supports: US-01 (customer selection for order intake).
         *     Returns a PageResponse (includes first field).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Free-text search by name or contact (optional) */
                    q?: string;
                    /** @description Registered from date (inclusive) */
                    from?: string;
                    /** @description Registered to date (inclusive) */
                    to?: string;
                    page?: number;
                    size?: number;
                    sortBy?: string;
                    sortDir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated customers list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create customer
         * @description Creates a customer with first name, last name, contact number.
         *     Supports: US-01. Enforces: BR-REC-01.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCustomerRequest"];
                };
            };
            responses: {
                /** @description Customer created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customer by ID
         * @description Supports: US-01.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update customer
         * @description Updates customer contact details (firstName, lastName, contactNumber).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCustomerRequest"];
                };
            };
            responses: {
                /** @description Updated customer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/service-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List service rates
         * @description Returns pricing rules (load, 8 kg limit, extra minute rate).
         *     Supports: US-02 (order intake form).
         */
        get: {
            parameters: {
                query?: {
                    activeOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service rates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRateResponse"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create service rate (Admin only)
         * @description Creates a new service rate. Requires ADMIN role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateServiceRateRequest"];
                };
            };
            responses: {
                /** @description Rate created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRateResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-rates/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active service rate
         * @description Returns the active rate used for order pricing (default).
         *     Supports: US-02. Enforces: BR-PR-01, BR-PR-02, BR-PR-03.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active rate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRateResponse"];
                    };
                };
                /** @description No active rate configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-rates/{rateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update service rate (Admin only)
         * @description Updates pricing rules. Admin controls pricing without code changes.
         *     Requires ADMIN role.
         *     Supports: ERD note "Admin can update without code changes".
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    rateId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateServiceRateRequest"];
                };
            };
            responses: {
                /** @description Updated rate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRateResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search orders
         * @description Returns orders with pagination and optional filters.
         *     Supports sortBy and sortDir params (default: createdAt desc).
         *     Supports free-text search via q param.
         *     Supports: US-01, US-03, US-07.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["OrderStatus"];
                    paymentStatus?: components["schemas"]["PaymentStatus"];
                    /** @description Start date (inclusive) */
                    from?: string;
                    /** @description End date (inclusive) */
                    to?: string;
                    /** @description Free-text search (tracking number, customer name, etc.) */
                    q?: string;
                    page?: number;
                    size?: number;
                    sortBy?: string;
                    sortDir?: "asc" | "desc";
                    /** @description Filter by specific customer ID */
                    customerId?: string;
                    /** @description Filter by service type (Rate ID) */
                    serviceRateId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated orders list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create laundry order
         * @description Creates order with automatic pricing (loads, extra minutes, add-ons).
         *     Generates unique tracking number. Sets initial status RECEIVED.
         *     createdByUserId is sourced from JWT when authenticated; falls back to body value.
         *     Returns 401 if neither JWT nor body provides the user identity.
         *     Supports: US-01, US-02. Enforces: BR-PR-01, BR-PR-02, BR-PR-03, BR-PR-04, BR-OL-01, BR-OL-02.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Order created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Validation or business rule error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized (no user identity) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview order pricing
         * @description Computes order totals (loads, base amount, extra minutes, add-ons, grand total)
         *     without creating an order. Uses active service rate. Supports live price preview.
         *     Supports: US-02.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrderPreviewRequest"];
                };
            };
            responses: {
                /** @description Price preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPreviewResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard order stats
         * @description Returns counts for staff dashboard: today's orders, in progress, ready for pickup, unpaid, today's revenue.
         *     Supports: UI/UX improvement plan.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Date for today (default: current date) */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/tracking/{trackingNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track order by tracking number
         * @description Public endpoint for customer tracking. Returns limited data (no internal IDs).
         *     Includes weightKg and totalLoads in addition to status/payment info.
         *     Supports: US-04. Enforces: BR-NOTIF-02, BR-OL-01.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackingNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order tracking view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderTrackingResponse"];
                    };
                };
                /** @description Tracking number not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/reference/{trackingNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track order by tracking number (Alias route)
         * @description Legacy/Alias endpoint for tracking order by tracking number.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trackingNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order tracking view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderTrackingResponse"];
                    };
                };
                /** @description Tracking number not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order by ID
         * @description Supports: US-03, US-05, US-06.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order details (extra minutes, add-ons)
         * @description Updates extra minutes and/or add-ons, recalculates totals.
         *     Allowed only when order is unpaid and not released.
         *     Client interview: "extended washing time due to excessive dirt — ₱1 per extra minute".
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderRequest"];
                };
            };
            responses: {
                /** @description Updated order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Validation or business rule error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order status
         * @description Updates status and records change in audit logs.
         *     changedByUserId is sourced from JWT when authenticated; falls back to body value.
         *     Returns 401 if neither JWT nor body provides the user identity.
         *     Supports: US-03, US-05. Enforces: BR-OL-03, BR-OL-04, BR-OL-05.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderStatusRequest"];
                };
            };
            responses: {
                /** @description Updated order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                /** @description Invalid transition or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized (no user identity) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payments
         * @description Returns payments with pagination and optional filters.
         *     Supports: US-07.
         */
        get: {
            parameters: {
                query?: {
                    orderId?: string;
                    /** @description Search by tracking number, customer name, or transaction ID */
                    q?: string;
                    /** @description Start date (inclusive) */
                    from?: string;
                    /** @description End date (inclusive) */
                    to?: string;
                    page?: number;
                    size?: number;
                    sortBy?: string;
                    sortDir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated payments list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentPageResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Record payment for order
         * @description Records payment. One payment per order. MVP: amount must equal order grand total.
         *     receivedByUserId is sourced from JWT when authenticated; falls back to body value.
         *     Returns 401 if neither JWT nor body provides the user identity.
         *     paymentMethod defaults to CASH if not provided.
         *     Supports: US-06. Enforces: BR-PAY-02, BR-PAY-03, BR-PAY-04.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePaymentRequest"];
                };
            };
            responses: {
                /** @description Payment recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description Validation or amount mismatch */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized (no user identity) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment by ID
         * @description Supports: US-07.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaymentResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/order/{orderId}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Void payment for order
         * @description Voids payment record and reverts order to UNPAID (or VOIDED).
         *     Supports: BR-PAY-06.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment voided */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Order or payment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search client alerts
         * @description Returns client alerts with pagination and optional filters.
         *     Ordered by createdAt descending by default.
         *     Supports: US-10.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Search by message, tracking number, or customer name */
                    q?: string;
                    status?: "PENDING" | "SENT" | "FAILED";
                    from?: string;
                    to?: string;
                    page?: number;
                    size?: number;
                    sortBy?: string;
                    sortDir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated client alerts list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientAlertPageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client-alerts/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark alert as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/client-alerts/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all alerts as read */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search audit logs
         * @description Returns forensic audit logs of system mutations (Admin only).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Search by table name, record ID, or user */
                    q?: string;
                    /** @description Filter by action type (e.g., ORDER_CREATE) */
                    action?: string;
                    from?: string;
                    to?: string;
                    page?: number;
                    size?: number;
                    sortBy?: string;
                    sortDir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditLogPageResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user statistics
         * @description Returns global counts of admins, active staff, and total users.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserStatsResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search users
         * @description Returns a complete list of all staff and admin accounts with pagination.
         *     Requires ADMIN role.
         *     Supports: US-11 (Admin audit & directory view).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Search by username, firstName, or lastName */
                    q?: string;
                    page?: number;
                    size?: number;
                    sortBy?: string;
                    sortDir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated users list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserPageResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create user
         * @description Onboards a new staff or admin member. Hashes password automatically.
         *     Requires ADMIN role.
         *     Supports: US-11 (Administrative control).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Username already exists or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user profile
         * @description Updates names, role, or password. Username remains immutable.
         *     Requires ADMIN role.
         *     Supports: US-11.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description Updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/users/{userId}/toggle-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle user status
         * @description Activates or deactivates a user account (soft-archive).
         *     Requires ADMIN role.
         *     Supports: US-11.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status toggled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/reports/sales/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily sales report
         * @description Aggregates income from payments for the given date.
         *     Requires ADMIN role.
         *     Supports: US-08. Enforces: BR-REC-01, BR-PAY-04.
         */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Daily sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailySalesReportResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly sales report
         * @description Aggregates income from payments for the given month.
         *     Requires ADMIN role.
         *     Supports: US-09. Enforces: BR-REC-01, BR-PAY-04.
         */
        get: {
            parameters: {
                query: {
                    year: number;
                    month: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monthly sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PeriodSalesReportResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales/yearly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yearly sales report
         * @description Aggregates income from payments for the given year.
         *     Requires ADMIN role.
         *     Supports: US-09. Enforces: BR-REC-01, BR-PAY-04.
         */
        get: {
            parameters: {
                query: {
                    year: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Yearly sales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PeriodSalesReportResponse"];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/sales/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sales trend report
         * @description Returns a list of daily sales aggregates (income, orders) for a given range.
         *     Max range is 31 days.
         *     Requires ADMIN role.
         */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales trend */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DailySalesReportResponse"][];
                    };
                };
                /** @description Forbidden - Admin only */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example weightKg must be greater than 0 */
            message: string;
            details?: string[];
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            /** @description JWT access token */
            accessToken: string;
            /** @description User role string (ADMIN or STAFF) */
            role: string;
            /** @description Token expiration time in seconds (e.g. 900 for 15m) */
            expiresIn: number;
        };
        CurrentUserResponse: {
            /** @description UUID string */
            userId: string;
            username: string;
            /** @description User role string (ADMIN or STAFF) */
            role: string;
        };
        /** @enum {string} */
        UserRole: "ADMIN" | "STAFF";
        /** @enum {string} */
        OrderStatus: "RECEIVED" | "WASHING" | "DRYING" | "FOLDING" | "READY_FOR_PICKUP" | "RELEASED" | "CANCELLED";
        /** @enum {string} */
        PaymentStatus: "UNPAID" | "PAID" | "PARTIAL" | "VOIDED" | "REFUNDED";
        /** @enum {string} */
        PaymentMethod: "CASH" | "GCASH" | "BANK_TRANSFER";
        /** @enum {string} */
        ClientAlertStatus: "PENDING" | "SENT" | "FAILED";
        CreateCustomerRequest: {
            firstName: string;
            lastName: string;
            contactNumber: string;
        };
        CustomerResponse: {
            /** Format: uuid */
            id: string;
            firstName: string;
            lastName: string;
            contactNumber: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CustomerPageResponse: {
            content: components["schemas"]["CustomerResponse"][];
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        ServiceRateResponse: {
            /** Format: uuid */
            id: string;
            serviceName: string;
            /** Format: double */
            basePricePerLoad: number;
            /** Format: double */
            kgLimitPerLoad: number;
            /** Format: double */
            pricePerExtraMinute: number;
            isActive: boolean;
        };
        UpdateServiceRateRequest: {
            serviceName?: string;
            /** Format: double */
            basePricePerLoad?: number;
            /** Format: double */
            kgLimitPerLoad?: number;
            /** Format: double */
            pricePerExtraMinute?: number;
            isActive?: boolean;
        };
        CreateServiceRateRequest: {
            serviceName: string;
            /** Format: double */
            basePricePerLoad: number;
            /** Format: double */
            kgLimitPerLoad: number;
            /** Format: double */
            pricePerExtraMinute: number;
            /** @default true */
            isActive: boolean;
        };
        CreateOrderRequest: {
            /** Format: uuid */
            customerId?: string;
            /**
             * Format: uuid
             * @description Optional — overridden by JWT principal when authenticated.
             */
            createdByUserId?: string;
            customer?: components["schemas"]["CreateCustomerRequest"];
            /** Format: double */
            weightKg: number;
            /** @default 0 */
            extraMinutes: number;
            initialAddOns?: components["schemas"]["AddOnInput"][];
            /** @description Optional list of machine UUIDs pre-assigned at intake. */
            machineIds?: string[];
        };
        AddOnInput: {
            name: string;
            /** Format: double */
            price: number;
            /** @default 1 */
            quantity: number;
        };
        OrderPreviewRequest: {
            /** Format: double */
            weightKg: number;
            /** @default 0 */
            extraMinutes: number;
            serviceType?: string;
            initialAddOns?: components["schemas"]["AddOnInput"][];
        };
        OrderPreviewResponse: {
            totalLoads: number;
            /** Format: double */
            baseAmount: number;
            /** Format: double */
            extraMinutesAmount: number;
            /** Format: double */
            addonsTotalAmount: number;
            /** Format: double */
            grandTotal: number;
        };
        OrderStatsResponse: {
            todaysOrders: number;
            inProgress: number;
            readyForPickup: number;
            unpaidOrders: number;
            /** Format: double */
            todaysRevenue: number;
        };
        UpdateOrderRequest: {
            extraMinutes?: number;
            addOns?: components["schemas"]["AddOnInput"][];
        };
        UpdateOrderStatusRequest: {
            /** @description Target OrderStatus value (e.g. WASHING, READY_FOR_PICKUP). */
            newStatus: string;
            notes?: string;
            /**
             * Format: uuid
             * @description Optional — overridden by JWT principal when authenticated.
             */
            changedByUserId?: string;
        };
        OrderResponse: {
            /** Format: uuid */
            id: string;
            trackingNumber: string;
            /** Format: uuid */
            customerId: string;
            customerName?: string;
            /** @description UUID string */
            createdByUserId?: string;
            /** @description Username of the staff who created the order */
            createdByUsername?: string;
            /** Format: uuid */
            serviceRateId?: string;
            /** Format: double */
            weightKg: number;
            totalLoads: number;
            extraMinutes?: number;
            /** Format: double */
            baseAmount: number;
            /** Format: double */
            extraMinutesAmount: number;
            /** Format: double */
            addonsTotalAmount: number;
            /** Format: double */
            grandTotal: number;
            addOns?: components["schemas"]["AddOnResponse"][];
            currentStatus: string;
            paymentStatus: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            auditLogs?: components["schemas"]["AuditLogResponse"][];
        };
        AddOnResponse: {
            name: string;
            /** Format: double */
            price: number;
            quantity: number;
        };
        OrderPageResponse: {
            content: components["schemas"]["OrderResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        PaymentPageResponse: {
            content: components["schemas"]["PaymentResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        OrderTrackingResponse: {
            trackingNumber: string;
            currentStatus: string;
            customerName: string;
            contactNumber?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: double */
            grandTotal?: number;
            paymentStatus: string;
            /** Format: double */
            weightKg?: number;
            totalLoads?: number;
            isRush?: boolean;
        };
        CreatePaymentRequest: {
            /** Format: uuid */
            orderId: string;
            /** Format: double */
            amountPaid: number;
            /** @description Defaults to CASH if not provided. */
            paymentMethod?: components["schemas"]["PaymentMethod"];
            /**
             * Format: uuid
             * @description Optional — overridden by JWT principal when authenticated.
             */
            receivedByUserId?: string;
            /** @description Reference / Transaction ID for non-cash payments (GCash, Bank). */
            paymentReference?: string;
        };
        PaymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            orderTrackingNumber?: string;
            customerName?: string;
            /** Format: double */
            amountPaid: number;
            paymentMethod: string;
            /** @description UUID string */
            receivedByUserId?: string;
            /** @description Username of the staff who received the payment */
            receivedByUsername?: string;
            /** Format: date-time */
            paymentDate: string;
            remarks?: string;
            /** @description Reference / Transaction ID for digital payments. */
            paymentReference?: string;
        };
        ClientAlertResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            trackingNumber?: string;
            /** Format: uuid */
            customerId: string;
            customerName?: string;
            contactNumber?: string;
            message: string;
            /** @description ClientAlertStatus: PENDING, SENT, FAILED */
            status: string;
            isRead?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            sentAt?: string;
        };
        ClientAlertPageResponse: {
            content: components["schemas"]["ClientAlertResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        DailySalesReportResponse: {
            /** Format: date */
            date: string;
            /** Format: double */
            totalIncome: number;
            paidOrdersCount: number;
            /** @description Revenue breakdown by payment method. */
            revenueByMethod?: {
                [key: string]: number;
            };
        };
        PeriodSalesReportResponse: {
            period: string;
            /** Format: double */
            totalIncome: number;
            paidOrdersCount: number;
        };
        AuditLogPageResponse: {
            content: components["schemas"]["AuditLogResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        /** @description Audit record of a system action. Capture point-in-time state for forensic inspection. */
        AuditLogResponse: {
            /** Format: uuid */
            id: string;
            /** @description Username who performed the action */
            actor: string;
            /**
             * @description Type of state change
             * @enum {string}
             */
            operation: "INSERT" | "UPDATE" | "DELETE" | "USER_LOGIN" | "USER_LOGOUT" | "PAYMENT_RECORD" | "ORDER_STATUS_UPDATE";
            /** @description Type of record affected (e.g., Order, Payment) */
            entityType?: string;
            /** @description Primary key of the affected record */
            entityId?: string;
            /** @description Forensic snapshot of state before mutation */
            oldState?: Record<string, never>;
            /** @description Forensic snapshot of state after mutation */
            newState?: Record<string, never>;
            /**
             * Format: date-time
             * @description Timestamp in UTC
             */
            createdAt: string;
            /** @description System method intercepted for this audit */
            methodName?: string;
            /** @description Human-readable description of the audit event */
            description?: string;
        };
        CreateUserRequest: {
            username: string;
            password: string;
            role: components["schemas"]["UserRole"];
            firstName: string;
            lastName: string;
        };
        UpdateUserRequest: {
            firstName?: string;
            lastName?: string;
            role?: components["schemas"]["UserRole"];
            password?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            username: string;
            role: components["schemas"]["UserRole"];
            firstName: string;
            lastName: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserPageResponse: {
            content: components["schemas"]["UserResponse"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
        };
        UserStatsResponse: {
            totalAdmins: number;
            totalActiveStaff: number;
            totalUsers: number;
        };
        /** @enum {string} */
        MachineStatus: "OPERATIONAL" | "MAINTENANCE" | "OUT_OF_ORDER";
        MachineResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["MachineStatus"];
            isActive: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateMachineRequest: {
            name: string;
        };
        UpdateMachineRequest: {
            name: string;
            status: components["schemas"]["MachineStatus"];
        };
        UpdateMachineStatusRequest: {
            status: components["schemas"]["MachineStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
