services:
  postgres:
    image: postgres:16
    container_name: laundry-postgres
    restart: always
    environment:
      POSTGRES_DB: laundry_db
      POSTGRES_USER: user(CHANGE)
      POSTGRES_PASSWORD: password(CHANGE)
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
