export const auditLog = {
  TITLE: "Audit Log",
  SUBTITLE: "Monitor system activity and review forensic records of administrative actions.",
  AUDIT_RECORD: "Activity Overview",
  AUDIT_INSPECTION: "Activity Details",
  SYSTEM_DETAILS: "Technical Overview",
  ACTION_CREATED: "Resource Created",
  ACTION_MODIFIED: "Resource Modified",
  ACTION_REMOVED: "Resource Deleted",
  IP_ADDRESS: "Network IP",
  USER_AGENT: "Device Signature",
  OUTCOME: "Action Result",
  ACTION: "Activity",
  ENTITY: "Module",
  SEARCH_LOGS: "Search by activity, module, or user...",
  ACTION_MAP: {
    INSERT: "Created",
    UPDATE: "Updated",
    DELETE: "Deleted",
    USER_LOGIN: "User Login",
    USER_LOGOUT: "User Logout",
    PAYMENT_RECORD: "Payment Processed",
    ORDER_STATUS_UPDATE: "Status Changed",
  } as Record<string, string>,
  TABLE_MAP: {
    payments: "Billing",
    customers: "Customer Relations",
    orders: "Service Orders",
    order_add_ons: "Order Add-ons",
    service_rates: "Pricing Configuration",
    users: "Access Management",
    notifications: "Communications",
    order_status_logs: "Status Workflow"
  } as Record<string, string>,
  AUDIT_METADATA: "Administrative Context",
  OPERATOR: "Performed By",
  OLD_DATA: "Before",
  NEW_DATA: "After",
} as const;
