export const clientAlerts = {
  TITLE: "Messaging",
  EMPTY_TITLE: "No Recent Messages",
  SUBTITLE: "Track and manage client SMS notifications.",
  SEARCH_MESSAGES: "Search by order # or message...",
  MESSAGE: "Message",
  STATUS: "Status",
  LOGGED_AT: "Sent At",
  VIEW_ORDER: "View Order",
  STATUS_VERIFIED: "Sent",
  STATUS_ACTION_REQUIRED: "Failed",
  DETAILS_TITLE: "Notification Details",
  SYSTEM_ALERT: "System Alert",
  SYSTEM_EVENT: "Automated Lifecycle Event",
  CHANNEL: "Delivery Channel",
  CHANNEL_INTERNAL: "Integrated SMS Gateway",
  DISMISS: "Close Details",
} as const;
