export const clientAlerts = {
  TITLE: "Client Alerts History",
  SUBTITLE: "History of automated SMS alerts sent to customers.",
  ACTIVITY_LOG: "Alert Log",
  MESSAGE: "Message Content",
  VIEW_ORDER: "View Order",
  STATUS_VERIFIED: "Sent",
  STATUS_ACTION_REQUIRED: "Failed",
  STATUS_PENDING: "Sending",
  DETAILS_TITLE: "Alert Details",
  SYSTEM_ALERT: "Client Alert",
  SYSTEM_EVENT: "SMS Transmission",
  LOGGED_AT: "Logged At",
  CHANNEL: "Channel",
  CHANNEL_INTERNAL: "SMS Gateway",
  DISMISS: "Dismiss",
  EMPTY_TITLE: "No alerts logged yet",
  EMPTY_DESC: "Automated alerts will appear here once orders reach 'Ready for Pickup'.",
} as const;
