export const dashboard = {
  TITLE: "Dashboard",
  SUBTITLE: "Today's summary for",
  ACCESSIBILITY_TITLE: "Faith Laundry Dashboard: Service Metrics and Live Order Pipeline",
  KPI_ACTIVE_LOADS: "Active Loads",
  KPI_READY_PICKUP: "Ready for Pickup",
  KPI_TODAYS_ORDERS: "New Orders",
  KPI_TODAYS_SALES: "Today's Sales",
  CURR_PROCESSING: "Currently processing",
  WAITING_CUST: "Waiting for customer",
  CREATED_TODAY: "Orders created today",
  AWAITING_PAYMENT: "Awaiting payment",
  QUEUE_TITLE: "Orders Queue",
  QUEUE_SUBTITLE: "Incoming orders will appear here automatically.",
  QUICK_ACTIONS: "Quick Actions",
  LIVE_UPDATES: "Live Updates",
  SHIFT_NOTE: "Staff Note",
  SHIFT_NOTE_TEXT: "Prioritize DRYING orders to free up machines.",
  ESTIMATED_TIME: "Estimated Time",
  CAPACITY_AVAILABLE: "Capacity available",
  QUEUE_ZONE: "Order Queue",
  WASHING_ZONE: "In Washer",
  DRYING_ZONE: "In Dryer",
  FOLDING_ZONE: "Folding",
  READY_ZONE: "Ready for Pickup",
  ADMIN_PANEL: "Admin Panel",
  WEEKLY_SALES: "Weekly Sales Performance",
} as const;
