export const machines = {
  TITLE: "Machines",
  SUBTITLE: "Manage laundry machines",
  NO_MACHINES: "No machines found.",
  NO_MACHINES_DESC: "Add a new machine to start tracking usage.",
  ADD_MACHINE: "Add Machine",
  EDIT_MACHINE: "Edit Machine",
  DELETE_MACHINE: "Delete Machine",
  CONFIRM_DELETE_TITLE: "Delete Machine",
  CONFIRM_DELETE_DESC: "Are you sure you want to delete this machine? This action cannot be undone.",
  TABLE_NAME: "Name",
  TABLE_STATUS: "Status",
  TABLE_CREATED_AT: "Created At",
  TABLE_ACTIONS: "Actions",
  STATUS_OPERATIONAL: "Operational",
  STATUS_MAINTENANCE: "Maintenance",
  STATUS_OUT_OF_ORDER: "Out of Order",
  FORM_NAME_LABEL: "Machine Name",
  FORM_STATUS_LABEL: "Status",
  ASSIGN_MODAL_TITLE: "Assign Machines to Order",
  ASSIGN_MODAL_DESC_PREFIX: "Order ",
  ASSIGN_MODAL_DESC_SUFFIX: " is moving to ",
  ASSIGN_MODAL_DESC_SUFFIX_2: ". Select the machines that will be used.",
  ASSIGN_MODAL_LOADING: "Loading machines...",
  ASSIGN_MODAL_NO_MACHINES: "No operational machines available in the system.",
  ASSIGN_MODAL_IN_USE: "In Use",
  ASSIGN_MODAL_ERROR_MAX: "Maximum of 10 machines can be assigned per order.",
  ASSIGN_MODAL_ERROR_MIN: "Please assign at least one machine to proceed.",
  ASSIGN_MODAL_CONFIRM: "Assign & Continue",
  MACHINE_SINGULAR: "Machine",
  MACHINE_PLURAL: "Machines",
} as const;
