export const orders = {
  TITLE: "Orders",
  CREATE_TITLE: "New Order",
  SUBTITLE: "Manage current laundry orders.",
  HISTORY: "Order History",
  DETAILS: "Order Details",
  WEIGHT: "Weight",
  LOADS: "Loads",
  EXTRA_TIME: "Extra Time",
  TRACKING: "View Tracking",
  PRICING_SUMMARY: "Price Summary",
  NEXT_STEP: "Next Step",
  ONE_TAP_WASH: "Start Washing",
  ONE_TAP_DRY: "Move to Dryer",
  ONE_TAP_FOLD: "Start Folding",
  ONE_TAP_READY: "Mark Ready",
  ONE_TAP_PICKUP: "Confirm Pickup",
  ADD_ONS: "Add-ons",
  VIEW_RECEIPT: "View Receipt",
  SERVICE_FEE: "Service Fee",
  EXTRA_TIME_FEE: "Extra Time Fee",
  EXTRAS: "Extras",
  PAYMENT_REQUIRED: "Payment Required before Pickup",
  SERVICE_TYPE: "Service Type",
  CHOOSE_SERVICE: "Choose Service",
  SPECIAL_INSTRUCTIONS: "Special Instructions",
  RECEIPT_SAVED: "Receipt saved as image",
  RECEIPT_DOWNLOAD_FAILED: "Download failed. Use Print instead.",
  ORDER_PREVIEW: "Order Preview",
  SETTLEMENT_REQUIRED: "Settlement Required",
  POST_PAID_ORDER: "Post-Paid Order",
  BILLING_STATUS: "Billing Status",
  PAYMENT_TIMING: "Payment Timing",
  COLLECT_PAYMENT_NOW: "Collect Payment Now",
  CUSTOMER: "Customer",
  AWAITING_DATA: "Awaiting data...",
  SYNCING: "Syncing...",
  TOTAL_PAYABLE: "Total Payable",
} as const;
