export const payments = {
  TITLE: "Payments",
  SUBTITLE: "Monitor financial inflows and process payment records.",
  SEARCH_PAYMENTS: "Search by reference # or customer...",
  LEDGER: "Payment Ledger",
  EXPORT: "Save as List",
  METHOD_CASH: "Cash",
  METHOD_GCASH: "GCash",
  METHOD_BANK: "Bank Transfer",
  VOIDED: "Void Payment",
  RECORD_PAYMENT: "Record Payment",
  VERIFICATION: "Payment Verification",
  VERIFIED_TRANSACTION: "Verified Transaction",
  RECEIVED_BY: "Received By",
  REMARKS: "Remarks",
} as const;
