export const rates = {
  TITLE: "Service Rates",
  SUBTITLE: "Manage pricing for laundry services.",
  BASE_PRICE: "Base Price",
  WEIGHT_LIMIT: "Weight Capacity",
  EXTRA_CHARGE: "Overtime Rate",
  OFFERED: "Active",
  NOT_OFFERED: "Inactive",
  ACCESS_RESTRICTED: "Administrative Access Only",
  ACCESS_DESC: "Pricing can only be modified by system administrators.",
  SERVICE_PREFIX: "Service #",
  SUSPENDED_LABEL: "Inactive",
  MODIFY_RATE: "Modify Rate",
  SERVICE_LABEL: "Service Name",
  KG_CAPACITY: "Capacity (KG)",
  EXTRA_SURCHARGE: "Extra Minute Rate",
  MAINTAIN_ACTIVE: "Keep this service active for customers",
  COMMIT_CHANGES: "Save Rate Changes",
  BASE_RATE: "Standard Rate",
  LOAD_CAPACITY: "Weight Capacity",
  HARDWARE_LIMIT: "Machine hardware limit",
  EXTRA_TIME_SURCHARGE: "Overtime Rate",
  PER_MINUTE: "Per Extra Minute",
  CREATE_RATE: "Add New Rate",
  EDIT_RATE: "Modify Service Rate",
} as const;
