export const rates = {
  TITLE: "Service Rates",
  SUBTITLE: "Manage pricing for laundry services.",
  BASE_PRICE: "Base Price (PHP)",
  WEIGHT_LIMIT: "Weight Limit per Load",
  EXTRA_CHARGE: "Extra Minute Charge (PHP)",
  OFFERED: "Currently offered",
  NOT_OFFERED: "Not Offered",
  ACCESS_RESTRICTED: "Only for Owners",
  ACCESS_DESC: "Pricing can only be changed by the owner.",
  SERVICE_PREFIX: "Service #",
  SUSPENDED_LABEL: "Suspended",
  MODIFY_RATE: "Modify Rate",
  SERVICE_LABEL: "Service Name",
  KG_CAPACITY: "Weight Limit (KG)",
  EXTRA_SURCHARGE: "Extra Minute Charge (PHP)",
  MAINTAIN_ACTIVE: "Keep this service active for customers",
  COMMIT_CHANGES: "Commit Changes",
  BASE_RATE: "Base Rate",
  LOAD_CAPACITY: "Load Capacity",
  HARDWARE_LIMIT: "Machine hardware limit",
  EXTRA_TIME_SURCHARGE: "Extra Time Surcharge",
  PER_MINUTE: "Per Extra Minute",
} as const;
