export const reports = {
  TITLE: "Sales Reports",
  SUBTITLE: "Track your shop's revenue and trends.",
  TOTAL_REVENUE: "Total Sales",
  PAID_ORDERS: "Paid Orders",
  AVG_SALE: "Average Sale",
  REPORT_PERIOD: "Report Period",
  REVENUE_SUMMARY: "Revenue Summary",
  DAILY: "Daily",
  WEEKLY: "Weekly",
  MONTHLY: "Monthly",
  YEARLY: "Yearly",
  EXPORT_PDF: "Export PDF",
  EXPORT_CSV: "Export to CSV",
  INFO_TEXT: "Insights are calculated based on settled (PAID) orders only.",
  PROCESSED_PAYMENTS: "Processed Payments",
  COMPLETED_TRANS: "Completed Transactions",
  PER_ORDER_REV: "Revenue per Order",
  PERIOD_SELECTION: "Period Selection",
  SELECT_DATE: "Select Date",
  MONTH: "Month",
  YEAR: "Year",
  SALES_HISTORY: "Detailed Sales History",
} as const;
