export const users = {
  TITLE: "Staff Management",
  SUBTITLE: "Manage system access and roles.",
  SEARCH_USERS: "Search by name or username...",
  CREATE: "Onboard Staff",
  MODIFY: "Modify Profile",
  CREATE_USER: "Onboard Staff",
  EDIT_USER: "Edit Profile",
  ROLE: "Role",
  USERNAME: "Username",
  PASSWORD: "Password",
  PASSWORD_HINT: "Leave blank to keep current password",
  ROLE_ADMIN: "Administrator",
  ROLE_STAFF: "Staff Member",
  REVOKE_ACCESS: "Revoke Access",
  RESTORE_ACCESS: "Restore Access",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  EMPTY_TITLE: "No staff members found",
  EMPTY_DESC: "Onboard your team to start managing operations.",
  JOINED: "Joined",
} as const;
